version: "3.9"

services:
  app:
    image: ${IMAGE}
    container_name: mellow-labs-dashboard
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - PORT=3000
      - DATABASE_PATH=/data/finance.db
      - APP_VERSION=${APP_VERSION:-latest}
    volumes:
      - ${HOST_DATA_PATH:-app-data}:/data
    restart: unless-stopped

volumes:
  app-data:
    driver: local

