version: "3.9"

services:
  app:
    build: .
    image: mellow-biz:local
    container_name: mellow-biz
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DATABASE_PATH=/data/finance.db
      - APP_VERSION=local
    volumes:
      - app-data:/data
    restart: unless-stopped

volumes:
  app-data:
    driver: local
