version: "3.9"

services:
  dashboard:
    build: .
    ports:
      - "8080:5000"
    environment:
      DATABASE_PATH: /data/finance.db
      UPLOADS_DIR: /data/uploads
      PORT: 5000
    volumes:
      - dashboard_data:/data
    restart: unless-stopped

volumes:
  dashboard_data:
